from pathlib import Path

GPU_BATCH_SIZE = 4
GRADIENT_BATCH_SIZE = 128

PATH_LENGTH_REGULIZER_FREQUENCY = 32

CONDITION_ON_MAPPER = True
CHANNELS = 1
NETWORK_CAPACITY = 16
STYLE_DEPTH = 8
IMAGE_SIZE = 64
LATENT_DIM = 512

EXTS = ['jpg', 'png']
FOLDER = "E:\\datasets\\GochiUsa_128\\train"

HOMOGENEOUS_LATENT_SPACE = True
USE_DIVERSITY_LOSS = False

NUM_TRAIN_STEPS = 10**6
EVALUATE_EVERY = 100
SAVE_EVERY = 2500

NAME = "default"
CURRENT_DIR = Path('.')
LOG_FILENAME = CURRENT_DIR / 'logs.csv'
MODELS_DIR = CURRENT_DIR / 'models'
RESULTS_DIR = CURRENT_DIR / 'results'

NEW = True
LOAD_FROM = -1

GPU = '0'
EPS = 1e-8
LEARNING_RATE = 2e-4
